### ISSUE TITLE
Correct branch name

### ISSUE THREAD

**Issue by m-aciek** [python/python-docs-it#4]
@alessandrocucci Hi, I'm interested in adding the Italian translation to docs-buildscript repository to put the translation on docs.python.org. Would you be able to rename the main branch to 3.11? That would allow docs-buildscript repo to discover the translation to build it.

Regards,
Maciej

**Comment by alessandrocucci** [comment]
Hello, I'm sorry but I think I can't do this. I have no access to the project settings. I created a branch named 3.11 but I cannot make it the default one, nor I can delete the current master branch.

**Comment by m-aciek** [comment]
For what it's worth what you already did should be enough for [docsbuild-scripts](https://github.com/python/docsbuild-scripts) to use the translations while building the docs. Thank you! Therefore I'm closing the ticket.

PS @JulienPalard would it be possible for you to grant @alessandrocucci with higher privileges in the repository?

**Comment by JulienPalard** [comment]
No, I'm not admin in this repo. Maybe @ewdurbin can?

**Comment by ewdurbin** [comment]
@JulienPalard upgraded you to Admin role on this repo.
